# Generated by Django 4.2.3 on 2023-07-19 09:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название опции')),
                ('js_name', models.CharField(max_length=10, verbose_name='Название поля для JS')),
            ],
            options={
                'verbose_name': 'опция торта',
                'verbose_name_plural': 'опции торта',
            },
        ),
        migrations.CreateModel(
            name='OptionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Наименование параметра')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена параметра')),
                ('ordering', models.IntegerField(verbose_name='Порядок отображения')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.optiontype')),
            ],
            options={
                'verbose_name': 'цена опции',
                'verbose_name_plural': 'цена опций',
            },
        ),
    ]
