# Generated by Django 4.2.3 on 2023-07-20 09:32

from django.db import migrations


db_costs = {
    'Levels': [0, 400, 750, 1100],
    'Forms': [0, 600, 400, 1000],
    'Toppings': [0, 0, 200, 180, 200, 300, 350, 200],
    'Berries': [0, 400, 300, 450, 500],
    'Decors': [0, 300, 400, 350, 300, 200, 280],
    'Words': 500
}


db_data = {
    'Levels': ['не выбрано', '1', '2', '3'],
    'Forms': ['не выбрано', 'Круг', 'Квадрат', 'Прямоугольник'],
    'Toppings': ['не выбрано', 'Без', 'Белый соус', 'Карамельный', 'Кленовый', 'Черничный', 'Молочный шоколад', 'Клубничный'],
    'Berries': ['нет', 'Ежевика', 'Малина', 'Голубика', 'Клубника'],
    'Decors': [ 'нет', 'Фисташки', 'Безе', 'Фундук', 'Пекан', 'Маршмеллоу', 'Марципан']
}

options_type = [
    ('Количесвто уровней','Levels'),
    ('Форма', 'Forms'),
    ('Топпинг', 'Toppings'),
    ('Ягоды', 'Berries'),
    ('Декор', 'Decors'),
    ('Надпись', 'Words')
]

def upload_init_options(apps, schema_editor):
    OptionType = apps.get_model('main', 'OptionType')
    OptionPrice = apps.get_model('main', 'OptionPrice')
    
    
    for option_name, js_name in options_type:
        order = 0
        option_type = OptionType.objects.create(name=option_name, js_name=js_name)
        
        if js_name == 'Words':
            OptionPrice.objects.create(
                type=option_type,
                name='Любая надпись',
                price=500,
                ordering=order
            )
        else:
            data = list(zip(db_data[js_name], db_costs[js_name]))
            for name, price in data:
                OptionPrice.objects.create(
                    type=option_type,
                    name=name,
                    price=price,
                    ordering=order
                )
                order+=1
    



class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(upload_init_options)
    ]
