# Generated by Django 4.2.3 on 2023-07-21 03:52

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cake_cakeuser_categorycake_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakeuser',
            name='address',
        ),
        migrations.AddField(
            model_name='cakeuser',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='main.categorycake', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='cakeuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None, verbose_name='Телефон клиента'),
        ),
    ]
