# Generated by Django 4.2.3 on 2023-07-23 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_remove_cakeuser_address_cakeuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakeuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cake_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
